version: '3.8'
services:
    node-express:
        container_name: vsnippet-cors-classic-11
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "127.0.0.1:1337:1337"